### ISSUE TITLE
[Agenda Item] Non-member participation

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/projects#35]
**Overview**:
> This question has come up a few times in the community WG. We would like stronger written clarity on the roles of non-members in GSF projects. For example
- Speakers Bureau is currently open to non-members
- There is a lack of clarity of whether non-member organisations could **host** a meetup event
- There are questions around how smaller organisations (freelancers or very early stage startups) can participate as the joining fee is probably not sustainable. Could we have a programme for those participants? Or an 'associate' status for a nominal fee limited to 1 IC participation?
- How can we promote grassroots participation?
- It has been suggested we should allow CNCF members to participate in certain activities?
- Related: We would like to propose a student programme (issue to follow). 

**Related topic**: The type of agenda item you want to propose.
- [ ] Governance: New project
- [X] Governance: Other
- [ ] Process
- [X] External Engagement
- [ ] Technology
- [ ] Other

**Related working groups**:

- [X] Community
- [X] Open Source
- [ ] Policy
- [ ] Standards
- [X] Oversight Committee

**Related issues or discussions**:

https://github.com/Green-Software-Foundation/oc/discussions/16

https://github.com/Green-Software-Foundation/oc/discussions/12

https://github.com/Green-Software-Foundation/oc/discussions/11

https://github.com/Green-Software-Foundation/community-wg/issues/60

**More information**:
> Any other information you want to add.

**Comment by Sealjay** [comment]
Really looking forward to chatting on this one. We have answers to some of this already, particularly on non-member code, working group, and the sleeker bureau.

But you're right to callout meet-ups and university engagements as a grey area.

I'm excited about this one

**Comment by adamj89** [comment]
Here's the student discussion: https://github.com/Green-Software-Foundation/community-wg/discussions/61

**Comment by Sealjay** [comment]
@adamj89 I’ve added #16 #12 and #11 as we’ve had an ongoing discussions about conferences from the point of view of including our open source projects,  university engagement (as we have activities and discussions ongoing), and non member involvement.

and #25 where we talked about accepting non member contributions.

**Comment by tmcclell** [comment]
OC informal discussion favors IC participation. Defer to Steering Committee decision.

**Comment by Sealjay** [comment]
Excellent

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Willmish** [comment]
> OC informal discussion favors IC participation to be allowed to contribute to projects and to be an observer to working group meetings without decision making responsibilities but can contribute verbally. Defer to Steering Committee for final decision and updates to the charter. @Sealjay @adamj89

Strongly in favour of that.
