### ISSUE TITLE
2024-02-06 Oversight Committee Agenda

### ISSUE THREAD

**Issue by Sophietn** [Green-Software-Foundation/projects#77]
## Agenda - 2024-02-06

Time 16:30 (UTC) - See the time in your [timezone](https://everytimezone.com/s/5c485561)

- Chair – Tammy McClellan (Microsoft)  
- Vice-Chair – Chris Lloyd-Jones (Avanade)
- Convener – Russ Trow (GSF) and Sophie Trinder (GSF)

## Antitrust Policy
Joint Development Foundation meetings may involve participation by industry competitors, and it is the intention of the Joint Development Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

If you have questions about these matters, please contact your company counsel or counsel to the Joint Development Foundation, DLA Piper.

## Roll Call
Please add 'Attended' to this issue during the meeting to denote attendance.
Any untracked attendees will be added by the GSF team below:

## Agenda
- [x] Convene & Roll Call
- [x] [Review previous meeting](https://github.com/Green-Software-Foundation/oc/issues/65)
- [x] Review/Approve agenda

- [x] [Discussion: Async-First Experiment with Oversight Committee ](https://github.com/Green-Software-Foundation/oc/discussions/69)

Problems identified through the Async discussion 
- What is the OC's purpose? People aren't showing up because this isn't clear 
- Governance stuff isn't interesting, it's critical but members don't really mind. If GSF just provide an oversight and chance to object that's all that is needed. For volunteers to attend, there's got to be something to learn or something to contribute to. 
- WG or project updates (what projects are doing, what projects need to improve) is what members really care about and want. This is missing. Would this be in the OC call? - Suggestion to start a quarterly webinar, WG chairs share update, via a slide deck 
- An advisory group to the SC - on topics that members really care about 
- Asim's attendance would help, to know the OC are being listened to by ED 

## Projects

[**GSF Project Tracker**](https://airtable.com/appVPOiFrCIjAAcvB/shrNADml6TRL1bm4j)

### Project Lifecycle

- [x] https://github.com/Green-Software-Foundation/oc/issues/75 
- Motion to approve Updated Document Project Lifecycle and [PR](https://github.com/Green-Software-Foundation/oc/pull/74) to add to OC website?
- [ ] https://github.com/Green-Software-Foundation/oc/issues/76
- [ ] An update on the progress towards https://github.com/Green-Software-Foundation/oc/issues/56 

## Governance

- [ ] [Elected WG Chairs](https://greensoftwarefoundation.atlassian.net/wiki/spaces/~612dd45e45cd76006a84071a/pages/93814822/Elections#Current-Working-Group-Chairs) 
- [ ] https://github.com/Green-Software-Foundation/oc/issues/37#issuecomment-1833275439

## AOB
- [ ] ?

## Next meeting
- [ ] 5th March - Sync or async? 

## Adjourn
- [ ] Any objections?

**Comment by tmcclell** [comment]
attended

**Comment by PindyBhullar** [comment]
Attended

**Comment by Henry-WattTime** [comment]
Attended

**Comment by Sophietn** [comment]
Both @russelltrow and myself also attended.
